alias github='cd /i/Github/Digit-210'
alias githubq='cd "Q:/SP26/gwr5195/Github/Digit-210"'
alias gs='git status'
alias gc='git commit -m'
alias gp='git push'
alias gl='git pull'
alias gaa='git add .'
